// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// If the firebase_core package isn't available in this environment,
// provide a minimal local definition of FirebaseOptions so static
// analysis and builds that don't require the real package can succeed.
// Remove this fallback when adding firebase_core to pubspec.yaml.
class FirebaseOptions {
  final String? apiKey;
  final String? appId;
  final String? messagingSenderId;
  final String? projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? measurementId;
  final String? iosClientId;
  final String? iosBundleId;

  const FirebaseOptions({
    this.apiKey,
    this.appId,
    this.messagingSenderId,
    this.projectId,
    this.authDomain,
    this.storageBucket,
    this.measurementId,
    this.iosClientId,
    this.iosBundleId,
  });
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtbgjxuqocBIZiPm7FeE4alt3D6nxzIkM',
    appId: '1:708125558269:web:3a59c3f3462d4e36eb8594',
    messagingSenderId: '708125558269',
    projectId: 'roleroster-68ac9',
    authDomain: 'roleroster-68ac9.firebaseapp.com',
    storageBucket: 'roleroster-68ac9.firebasestorage.app',
    measurementId: 'G-HDEBMF8FXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzow7XtaC6QOmsfDIuAyqFlSnBrMkNF9U',
    appId: '1:708125558269:android:d3e9e5cac7213033eb8594',
    messagingSenderId: '708125558269',
    projectId: 'roleroster-68ac9',
    storageBucket: 'roleroster-68ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRrZPTMWr5ZOTmOzP2cxl9o6xg7batwI',
    appId: '1:708125558269:ios:3f6bedc04f6e563aeb8594',
    messagingSenderId: '708125558269',
    projectId: 'roleroster-68ac9',
    storageBucket: 'roleroster-68ac9.firebasestorage.app',
    iosClientId:
        '708125558269-tp5t1q6dcvt98ujp6h5qdvnpm9p0ki7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolerosterRfourlApplicationTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRrZPTMWr5ZOTmOzP2cxl9o6xg7batwI',
    appId: '1:708125558269:ios:3f6bedc04f6e563aeb8594',
    messagingSenderId: '708125558269',
    projectId: 'roleroster-68ac9',
    storageBucket: 'roleroster-68ac9.firebasestorage.app',
    iosClientId:
        '708125558269-tp5t1q6dcvt98ujp6h5qdvnpm9p0ki7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolerosterRfourlApplicationTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtbgjxuqocBIZiPm7FeE4alt3D6nxzIkM',
    appId: '1:708125558269:web:3c2407e73c9f5cfbeb8594',
    messagingSenderId: '708125558269',
    projectId: 'roleroster-68ac9',
    authDomain: 'roleroster-68ac9.firebaseapp.com',
    storageBucket: 'roleroster-68ac9.firebasestorage.app',
    measurementId: 'G-R9NNZBH1TG',
  );
}
