// lib/main.dart
// REPLACE your existing main.dart with this file entirely.

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart' as firebase_options;
import 'theme/app_theme.dart';
import 'screens/login_screen.dart';

// Hive models
import 'hive_models/task_model.dart';

// Providers
import 'providers/auth_provider.dart';
import 'providers/group_provider.dart';
import 'providers/task_provider.dart';
import 'providers/profile_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Firebase ───────────────────────────────────────────────────────────────
  await Firebase.initializeApp(
    options: firebase_options.DefaultFirebaseOptions.currentPlatform
        as FirebaseOptions?,
  );

  // ── Hive (local database) ──────────────────────────────────────────────────
  await Hive.initFlutter();
  Hive.registerAdapter(TaskModelAdapter()); // generated by hive_generator
  await Hive.openBox<TaskModel>('tasks'); // offline task cache

  runApp(const RoleRosterApp());
}

class RoleRosterApp extends StatelessWidget {
  const RoleRosterApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => GroupProvider()),
        ChangeNotifierProvider(create: (_) => TaskProvider()),
        ChangeNotifierProvider(create: (_) => ProfileProvider()),
      ],
      child: MaterialApp(
        title: 'RoleRoster',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.theme,
        home: const LoginScreen(),
      ),
    );
  }
}
