// lib/main.dart
// REPLACE your existing main.dart with this file entirely.

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart' as firebase_options;
import 'theme/app_theme.dart';
import 'screens/login_screen.dart';

// Hive models
import 'hive_models/task_model.dart';
import 'hive_models/project_upload_model.dart';

// Providers
import 'providers/auth_provider.dart';
import 'providers/group_provider.dart';
import 'providers/notification_provider.dart';
import 'providers/project_upload_provider.dart';
import 'providers/task_provider.dart';
import 'providers/profile_provider.dart';
import 'services/fcm_service.dart';

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
    options: firebase_options.DefaultFirebaseOptions.currentPlatform,
  );
  // Background/terminated pushes are displayed by the OS when the payload
  // includes a notification block. This handler keeps Firebase initialized.
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Firebase ───────────────────────────────────────────────────────────────
  await Firebase.initializeApp(
    options: firebase_options.DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // ── FCM (push notifications) ─────────────────────────────────────────────
  await FcmService().init();

  // ── Hive (local database) ──────────────────────────────────────────────────
  await Hive.initFlutter();
  Hive.registerAdapter(TaskModelAdapter()); // generated by hive_generator
  Hive.registerAdapter(ProjectUploadModelAdapter());
  await Hive.openBox<TaskModel>('tasks'); // offline task cache
  await Hive.openBox<ProjectUploadModel>('project_uploads');
  await Hive.openBox('users');
  // open profiles cache box used for local avatar storage
  await Hive.openBox('profiles');

  runApp(const RoleRosterApp());
}

class RoleRosterApp extends StatelessWidget {
  const RoleRosterApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => GroupProvider()),
        ChangeNotifierProvider(create: (_) => NotificationProvider()),
        ChangeNotifierProvider(create: (_) => ProjectUploadProvider()),
        ChangeNotifierProvider(create: (_) => TaskProvider()),
        ChangeNotifierProvider(create: (_) => ProfileProvider()),
      ],
      child: MaterialApp(
        title: 'RoleRoster',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.theme,
        home: const LoginScreen(),
      ),
    );
  }
}
